# Generated by Django 5.0.6 on 2024-08-18 02:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessKey', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=155)),
                ('subject', models.CharField(max_length=155)),
                ('yearAndSection', models.CharField(max_length=155)),
                ('questionaire', models.JSONField()),
                ('answer', models.JSONField()),
                ('totalItem', models.IntegerField()),
                ('expirationDate', models.DateTimeField(default=datetime.datetime.now)),
                ('uniqueKey', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='quizStudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(blank=True, max_length=25, null=True)),
                ('lastName', models.CharField(max_length=155)),
                ('givenName', models.CharField(max_length=155)),
                ('middleName', models.CharField(max_length=155)),
                ('answer', models.JSONField()),
                ('score', models.IntegerField()),
                ('dateTaken', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentRecprd', to='record.quizrecord')),
            ],
        ),
    ]
