# Generated by Django 5.0.6 on 2024-08-18 03:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='4f537e2cf2b9a74ca065a0fea902d80c4b72e8423380e96eb8e9ea38614670f6', max_length=155, unique=True)),
                ('dateLogin', models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 41, 38, 449549))),
                ('expirationDate', models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 41, 38, 449549))),
                ('registeredUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registereduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
