# Generated by Django 5.0.6 on 2024-08-18 03:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_usertoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='dateLogin',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 44, 46, 138481)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 44, 46, 138481)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default='6f746e3e86ce36138714a8321954d55fe2d58ba5e7883476a815561bc3ccacdf', max_length=155, unique=True),
        ),
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=155)),
                ('address', models.TextField()),
                ('organization', models.CharField(max_length=150)),
                ('ogganizationAddress', models.TextField()),
                ('dateAccomplished', models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 44, 46, 138481))),
                ('registeredUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
