# Generated by Django 5.0.6 on 2024-08-18 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_usertoken_datelogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dateAccomplished',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 44, 55, 400696)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='dateLogin',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 44, 55, 399194)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 44, 55, 399194)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default='d2066b08d3171d9680c3d46e0cc94af958ae3da850c9cfe7b19390f966d970b7', max_length=155, unique=True),
        ),
    ]
