# Generated by Django 5.0.6 on 2024-08-18 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_useraccount_dateaccomplished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dateAccomplished',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 45, 38, 417713)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='dateLogin',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 45, 38, 417713)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 45, 38, 417713)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default='a6497932b5708716536b090e3b2ef9f0ddc2d3a3b06a27b4741600b8f1c5ef45', max_length=155, unique=True),
        ),
    ]
