# Generated by Django 5.0.6 on 2024-08-18 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_useraccount_dateaccomplished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dateAccomplished',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='dateLogin',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 46, 50, 442945)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 11, 46, 50, 442945)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default='edf65c73c55b0135c59378725c8f0c80e174c6c783cf7a8acfcea9b30d79ca7d', max_length=155, unique=True),
        ),
    ]
