# Generated by Django 5.0.6 on 2024-08-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_quizrecord_accesskey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizrecord',
            old_name='expirationDate',
            new_name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='quizrecord',
            name='uniqueKey',
        ),
    ]
