# Generated by Django 5.0.6 on 2024-08-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_rename_expirationdate_quizrecord_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizrecord',
            name='answer',
        ),
    ]
