# Generated by Django 5.0.6 on 2024-08-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_remove_quizrecord_totalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='totalItem',
            field=models.IntegerField(default=0),
        ),
    ]
