# Generated by Django 5.0.6 on 2024-08-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_quizrecord_totalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='multipleChoice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizrecord',
            name='trueOrFalse',
            field=models.IntegerField(default=0),
        ),
    ]
