# Generated by Django 5.0.6 on 2024-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_quizrecord_multiplechoice_quizrecord_trueorfalse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizrecord',
            old_name='questionaire',
            new_name='questionnaire',
        ),
    ]
