# Generated by Django 5.0.6 on 2024-08-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_quizrecord_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizrecord',
            old_name='activate',
            new_name='online',
        ),
    ]
